// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgsR3xb4hGtt5GZS5TqRuwFQZB9gN4JYY',
    appId: '1:13336682684:web:b511ec217a000d039df0b9',
    messagingSenderId: '13336682684',
    projectId: 'skymiles-19a43',
    authDomain: 'skymiles-19a43.firebaseapp.com',
    storageBucket: 'skymiles-19a43.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApkacYff0qr-EqHDIbZ4YtCdLkdZrbCEg',
    appId: '1:13336682684:android:5c9ee94d18d172ec9df0b9',
    messagingSenderId: '13336682684',
    projectId: 'skymiles-19a43',
    storageBucket: 'skymiles-19a43.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-BWI-LsxkHfCtwsJxlo_HDr11H2QbRwg',
    appId: '1:13336682684:ios:15d53514ccf346649df0b9',
    messagingSenderId: '13336682684',
    projectId: 'skymiles-19a43',
    storageBucket: 'skymiles-19a43.firebasestorage.app',
    iosBundleId: 'com.example.skymilesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-BWI-LsxkHfCtwsJxlo_HDr11H2QbRwg',
    appId: '1:13336682684:ios:15d53514ccf346649df0b9',
    messagingSenderId: '13336682684',
    projectId: 'skymiles-19a43',
    storageBucket: 'skymiles-19a43.firebasestorage.app',
    iosBundleId: 'com.example.skymilesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCgsR3xb4hGtt5GZS5TqRuwFQZB9gN4JYY',
    appId: '1:13336682684:web:80c3767160db6e0c9df0b9',
    messagingSenderId: '13336682684',
    projectId: 'skymiles-19a43',
    authDomain: 'skymiles-19a43.firebaseapp.com',
    storageBucket: 'skymiles-19a43.firebasestorage.app',
  );
}
